// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserSyncApi.Data;

#nullable disable

namespace UserSyncApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528011441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserSyncApi.Models.Mahasiswa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<List<string>>("MataKuliah")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NilaiUkt")
                        .HasColumnType("numeric");

                    b.Property<string>("ProgramStudi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAkademik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusTagihan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Mahasiswas");
                });

            modelBuilder.Entity("UserSyncApi.Models.RiwayatPembayaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("JumlahBayar")
                        .HasColumnType("numeric");

                    b.Property<string>("MahasiswaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalBayar")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MahasiswaId");

                    b.ToTable("RiwayatPembayarans");
                });

            modelBuilder.Entity("UserSyncApi.Models.RiwayatPembayaran", b =>
                {
                    b.HasOne("UserSyncApi.Models.Mahasiswa", "Mahasiswa")
                        .WithMany("RiwayatPembayaran")
                        .HasForeignKey("MahasiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("UserSyncApi.Models.Mahasiswa", b =>
                {
                    b.Navigation("RiwayatPembayaran");
                });
#pragma warning restore 612, 618
        }
    }
}
